#ifndef EMP_CIRCUIT_FLOAT_BUILTINS_H__
#define EMP_CIRCUIT_FLOAT_BUILTINS_H__

// Process-wide cache of the built-in float32 circuits. Each is an embedded
// .empbc blob (see float_builtins.cpp, generated by tools/float_to_empbc.py),
// parsed and validated exactly once on first use via std::call_once. The
// returned program is immutable and shared across threads; callers supply their
// own (thread-local) CircuitScratch to execute it. The enumerator order MUST
// match the kBlobs table in float_builtins.cpp.

#include "emp-tool/circuits/boolean_program.h"

namespace emp {
namespace circuit {

enum class BuiltinCircuit {
	Float32Add = 0,
	Float32Sub,
	Float32Mul,
	Float32Div,
	Float32Sq,
	Float32Sqrt,
	Float32Sin,
	Float32Cos,
	Float32Exp,
	Float32Exp2,
	Float32Ln,
	Float32Log2,
	Float32Eq,
	Float32Le,
	Float32Leq,
	Count
};

const BooleanProgram& builtin_circuit(BuiltinCircuit id);

}  // namespace circuit
}  // namespace emp
#endif  // EMP_CIRCUIT_FLOAT_BUILTINS_H__
